# Change these first
owner: bad-wolves # Your GitHub organization or username, where this repository lives
repo: status.badwolves.games # The name of this repository

sites:
  - name: Pterodactyl - Panel
    url: https://panel.badwolves.games
  - name: Pterodactyl - Node 01
    url: https://01.node.badwolves.games:50181
    expectedStatusCodes:
      - 401
  - name: Pterodactyl - Node 02
    url: https://02.node.badwolves.games:50182
    expectedStatusCodes:
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.badwolves.games
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/bad-wolves/status.badwolves.games/blob/8338e618964e1f5214c974adae809ebbab6ea660/assets/bad-wolves.png
  name: Bad Wolves Gaming
  introTitle: "**Bad Wolves Gaming** Systems Status Page"
  introMessage: A system status monitor for Bad Wolves Gaming.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
